### ISSUE TITLE
Roadmap and difference to Xivapi

### ISSUE THREAD

**Issue by zhyupe** [thewakingsands/cocoa#1]
## Endpoints
- [x] `/content`
- [x] `/{contentName}`
- [x] `/{contentName}/{contentId}`
- [ ] `/search`

## Known problems
- [x] ~Descriptions are not formatted.~
- [x] ~Transients are not merged to parent.~
- [ ] Nested property (links) are not displayed.
- [ ] Reverse links (GameContentLinks) are not displayed.

## Difference to Xivapi
- Object depth (nested property) will be reduced from 3 to 1.
- Some post-process params in game data api are not implemented (`print_query / minify / pretty / snake_case / remove_keys`).

**Comment by zhyupe** [comment]
Examples related to object depth changing:

**Response before change**
```
{
  "ItemIngredient0": {
    "ClassJobRepair": {
      "ItemSoulCrystal": {
        "ClassJobRepair": 0
      },
      "ItemSoulCrystalTarget": "Item",
      "ItemSoulCrystalTargetID": 10340
    },
    "ClassJobRepairTarget": "ClassJob",
    "ClassJobRepairTargetID": 11
  },
  "ItemIngredient0Target": "Item",
  "ItemIngredient0TargetID": 2121
}
```

**Response after change**
```
{
  "ItemIngredient0": {
    "ClassJobRepair": 11
  },
  "ItemIngredient0Target": "Item",
  "ItemIngredient0TargetID": 2121
}
```
